version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      MONGO_URI: "mongodb://mongodb:27017/mydatabase"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - redis
      - mongodb
    ports:
      - "3000:3000"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
